### ISSUE TITLE
'website' broken for GAVIRIA VELEZ JOSE OBDULIO

### ISSUE THREAD

**Issue by tmtmtmtm** [wfdd/colombia-senado-scraper#1]
The `website` value for "1153:gaviria-velez-jose-obdulio" is being set to 
```
http://www.pensamientocolombia.org
www.centrodemocrático.com
```

We can handle multiple values in this field if separated by a semi-colon, so we could potentially change the SQL of the import statement to replace the newline character there, but it would be better if it could be fixed in the scraper. Is this something you can do easily, or should we look into either submitting a patch or just working around it?

**Comment by wfdd** [comment]
This should be fixed now, though I've hit the dreaded 'nothing changed in the database' on morph.io, so it might be a while before the data flows through...

**Comment by tmtmtmtm** [comment]
Great, thanks!

**Comment by wfdd** [comment]
Confirmed to work in everypolitician/everypolitician-data#20664, so closing.

**Comment by tmtmtmtm** [comment]
Thanks @wfdd !
